### ISSUE TITLE
Negative Value

### ISSUE THREAD

**Issue by vikaz596** [browniefed/react-flip-ticker#6]
Animation not happening while changing 9.9 to -3.2 or vice versa.

**Current Behaviour**
Simply value gets displayed without animation.

**Expected Behaviour**
Value should be changed with animation.

**Comment by browniefed** [comment]
Possibly because of a length issue, try rendering an extra space in front of the non-negative text.
` 9.9`, so that when it switches to `-3.2` they're the same length.

If that doesn't work you may need to use the custom single flip tick option and craft your own spinner.

Otherwise I may look into this later, I honestly don't use this anymore so happy to accept a PR if someone looks into it.
